db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  host: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 11234
  properties:
    first: 1
    second: 12314
    third.value: third
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
app.common.logging:
  enabled: true
  level: INFO
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    root: INFO
    ru.madrabit.frankenstein.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: log_file.log
    path: /
#spring.profiles.active:qa
spring:
  mvc:
    format:
      date: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      show-sql: true
      format-sql: true
      hibernate:
        ddl-auto: validate
        default_batch_fetch_size: 50
    open-in-view: false
image:
  bucket:
    path: C:\\projects\\java\\frankenstein\\images